apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station
  labels:
    app: weather-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
      - name: weather-station
        image: weather_station:latest
        imagePullPolicy: IfNotPresent
        command: ["java", "-jar", "/app/weather_station.jar"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:latest
        imagePullPolicy: IfNotPresent
        command: ["java", "-jar", "/app/consumer.jar"]
