version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092                       # “Open this door on the inside.”                     -   where the broker listens for connections, inside the container (or VM).
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092   # “Tell visitors which doorbell to ring to get in.”   -   what the broker tells clients to use to reach it.
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  default:
    name: kafka-net
    driver: bridge
